---
title: "HomeWork4"
author: "Teresa"
date: "2024-02-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Question 1
# a)

```{R}
x <- 1.1
a <- 2.2
b <- 3.3
z <- x^(a*b)
print(z)
```
I defined the values of x, a, and b, and then defined the function while placing parenthesis to specify the order of operation.

# b)

```{R}
z <- (x^a)^b
print(z)
```
I placed x^a  in parenthesis to indicate that I'd like to calculate x to the power of b and then express the result to the power of b.

# c)
```{R}
z <- 3*x^3+2*x^2+1
print(z)
```
I use asterisks to indicate that I'm multiplying the digit by x expressed as a power of 3 and 2 respectively.  

## Question 2
# a) 

```{R}
x <- c(seq(1,8), seq(7,1))
print(x)
```
The c in the function combines everything. The first sequence is in ascending order from 1 to 8 and the second is from 7 to 1.


# b) 
```{R}
my_vec <-c(1,2,3,4,5)
rep(x=my_vec, times=my_vec)
```
I define my vectors and then say for each vector to be repeated in the corresponding number of times in my defined vectors

# c) 

```{R}
my_vec <-c(5,4,3,2,1)
times <- c(1,2,3,4,5)
rep(x=my_vec, times=times)
```
I started off by defining my vectors in descending order and then I follow it with a command that says how many times each of the vectors will be repeated. The rep command than lists my vectors, each repeated the number of times defined in the "times" function. 


## Question 3
```{R}
x <- runif(1,0,10)
y <- runif(1,0,10)
coordinates <- c(x,y)
print(coordinates)
radius <- sqrt(x^2 + y^2)
theta <- atan (x/y)
polar_coordinates <- c(radius,theta)
print(polar_coordinates)
```


## Question 4
```{R}
queue <- c("sheep", "fox", "owl", "ant")
queue <- c(queue, "serpent") # update the queue by adding "serpent".
print(queue)
queue <- queue[-1] # -1 denotes that I've taken the first element from the queue 
print(queue)
queue <- c("donkey",queue[queue!= "donkey"]) # donkey at the start of the queue denotes that it's the first element and then queue! = "donkey" takes away donkey from the original list of elements.
print(queue)
queue <- queue [queue!= "serpent"] # the expression in square brackets expresses that we do not want the defined element in the queue, serpent therefore gets removed.
print(queue)
queue <- queue[queue!="owl"] # the expression in square brackets expresses that we do not want the defined element in the queue, owl therefore gets removed. 
print(queue)
queue <-append(queue,"aphid",2)
print(queue)
aphid_position <- 
```


## Question 5